[package]
name = "brainwallet"
version = "0.2.2"
edition = "2021"

[dependencies]
sha256 = "1.5.0"
secp256k1 = "0.29.0"
bitcoin = "0.32.2"
hex = "0.4.3"
colored = "2.1.0"
clap = { version = "4.5.7", features = ["derive"] }
